- OWNERS
- README.md
- go.mod
- go.sum
- tests/e2e/installations_test.go
- tests/e2e/suite_test.go
- tests/helper/charts/charts.go
- tests/helper/charts/rancheralerting.go
- tests/helper/charts/rancherlogging.go
- tests/helper/charts/ranchermonitoring.go
Introduced label-based logging for executing end-to-end tests.
Added wait.poll for improved chart handling.
Removed dependencies and refactored code for better maintainability and performance.
> Enhance Testing and Codebase with Label-based E2E Logs, Chart Polling, and Dependency Cleanup

- tests/e2e/monitoring_e2e_test.go
Introduced rancher monitoring default alerts validation:
rancher default alert : watchdog
> Introduced rancher monitoring default alerts validation.

- go.mod
- tests/e2e/monitoring_e2e_test.go
- Adding test for create prometheus rule.
> Adding test for create prometheus rule.

- tests/e2e/installations_test.go
- tests/helper/charts/charts.go
- tests/helper/charts/prometheusfederator.go
Adding test for installing prometheus federator chart.
> Adding test for installing prometheus federator chart.

- .github/workflows/docker_run.yaml
- README.md
- tests/helper/charts/ranchermonitoring.go
- Adds a GitHub Actions workflow to automate Rancher RKE1 setup using docker, chart installation, and E2E tests.
- Sets up Go environment and installs dependencies for testing.
- Runs installation and E2E tests with results saved in XML and HTML formats.
- Uploads test artifacts and performs a container cleanup after the job.
> Automated Rancher Setup, Chart Installation, and E2E Testing Workflow

- tests/e2e/monitoring_e2e_test.go
After successful installation verifying status of below work load.
1. Deployments
2. Pods
3. Daemonsets
> Adding tests for verifying workload status

- tests/e2e/installations_test.go
- tests/helper/charts/charts.go
Fix installation failures and session hang issues.
> fix installation failure & session hang issue

- tests/e2e/rancher_alerts_e2e_test.go
- tests/helper/utils/utils.go
- tests/helper/yamls/alertManagerConfig.yaml
Added P0 tests for rancher alerts along with creation of AlertManagerConfig.
> Added P0 tests for rancher alerts along with creation of alert manager config.

- tests/e2e/monitoring_e2e_test.go
adding wait and retries to fix prometheus federation intermittent failure.
> adding wait and retries to fix prometheus federation intermittent failure.

- tests/e2e/rancher_alerts_e2e_test.go
- tests/e2e/rancher_logging_e2e_test.go
adding rancher logging P0 test along with minor cosmetic fixes
> adding rancher logging P0 test along with minor cosmetic fixes

- .github/workflows/master-e2e.yaml
- .github/workflows/observability-e2e.yaml
Automates Observability E2E tests using RKE2 clusters on AWS, improving deployment efficiency and ensuring seamless validation of monitoring, alerting, and logging workflows.
> Automate Observability E2E test execution with RKE2 Cluster

- go.mod
- go.sum
- tests/e2e/monitoring_e2e_test.go
- tests/e2e/rancher_alerts_e2e_test.go
- tests/e2e/rancher_logging_e2e_test.go
- tests/e2e/rancher_promfed_e2e_test.go
- tests/helper/charts/charts.go
- tests/helper/utils/utils.go
- tests/helper/yamls/projectMonitoringChart.yaml
Automated Level 0 Test cases 
1. Test : Verify status of rancher prometheus-federator (deployment + pod) using kubectl
2. Test : Project Monitoring for test-promfed-monitoring
> prometheus federator Level0 e2e test automation

- .github/workflows/docker_run.yaml
- .github/workflows/master-e2e.yaml
> fix pipeline failure

- .github/workflows/docker_run.yaml
Fixed release test execution workflow. Separated prime and non-prime test execution by updating repository URL logic.
> Fixed release test execution workflow

- resources/rancher/clusters.go
- tests/backuprestore/inplace_scenarios_test.go
Currently test leaking the cluster, adding step to remove the downstream clusters as part of test.
> added support to delete the downstream cluster

- .github/workflows/docker_run.yaml
- tests/e2e/after_upgrade_test.go
- tests/e2e/before_upgrade_test.go
- tests/helper/charts/charts.go
- tests/helper/charts/ranchermonitoring.go
Implement upgrade functionality for the Observability monitoring chart
> Added Observability monitoring chart upgrade

- tests/backuprestore/installations_test.go
- tests/helper/charts/rancherbackuprestore.go
- tests/helper/yamls/encrptionConfigwithAsterisk.yaml
Adds verification for the proper uninstallation of the Backup and Restore chart in Rancher, ensuring all related deployments and resources are removed.
> added uninstall chart verification with deployments

- tests/e2e/after_upgrade_test.go
- tests/e2e/before_upgrade_test.go
- tests/helper/charts/prometheusfederator.go
Implement upgrade functionality for the Observability prometheus federator chart
> Added Observability prometheus federator chart upgrade

- .github/workflows/backup-restore-e2e-trigger.yaml
- .github/workflows/backup-restore-e2e.yaml
This PR adds a reusable GitHub Actions workflow to run Rancher Backup-Restore end-to-end (E2E) tests using dynamically provisioned AWS EC2 infrastructure.
- Provisions EC2 instance via Terraform
- Installs Rancher Manager with specified version
- Generates API token for E2E test execution
- Runs tests against Rancher with backup/restore validation
- Supports AWS S3 remote state and Rancher Helm setup
Rancher & RKE2 versions, AWS credentials, SSH key, encryption key, etc.
- setup: Provisions instance, installs Rancher
- run-e2e: Runs E2E tests using generated Rancher config
- delete-resources: delete all the aws resources
> backup-restore test run pipeline 

- .github/workflows/backup-restore-e2e.yaml
This PR will update the rancher manager installation based on the version from docker or stage registry.
> fixed rancher install command for stage repo

- tests/e2e/after_upgrade_test.go
- tests/e2e/before_upgrade_test.go
- tests/helper/charts/rancherlogging.go
Added automation for logging chart upgrade scenarios
> Added automation for logging chart upgrade scenarios

- .github/workflows/backup-restore-migration-trigger.yaml
- .github/workflows/backup-restore-migration.yaml
- .gitignore
- cattle-config.yaml.example
- resources/terraform/config/variables.tf
- resources/terraform/modules/ec2/install_rancher.sh
- resources/terraform/modules/ec2/install_rke2.sh
- tests/backuprestore/migration/migration_suite_test.go
- tests/backuprestore/migration/migration_test.go
This PR adds a GitHub Actions workflow to automatically test the Rancher backup and restore migration scenario. The workflow helps validate compatibility and functionality across migration to ensure data integrity and service continuity.
https://github.com/omkarkhatavkar/observability-e2e/actions/runs/16290188616/job/45998122476
> added the github action workflow to test the migration scenario

- .github/workflows/docker_run.yaml
- .github/workflows/k3s_run.yaml
* Fixed quick pipeline failure detection
* Optimized log file checks with unified loop
* Clear success/failure messages with version details
> fix quick pipeline failure and optimized conditions

- tests/backuprestore/functional/backup_restore_metrics_test.go
- tests/backuprestore/functional/backup_test.go
- tests/backuprestore/functional/inplace_scenarios_test.go
Code fixed the schema error came after installation of chart and backup
> fixed the schema error came after installation of chart and backup

- .github/workflows/backup-restore-e2e-trigger.yaml
- .github/workflows/backup-restore-migration-rollback-trigger.yaml
There has been update in the secrets for the backup and restore. So there needs to be an update in the GHA.
> updated the secrets for the backup and restore
